### ISSUE TITLE
Beginner dotnet Mac OS install intstructions?

### ISSUE THREAD

**Issue by dps** [stevehjohn/AoC#54]
This looks really awesome, but I couldn't get it to work as a total dotnet on Mac newbie - might you be able to write some quick instructions on how to get started (either how to run the precompiled release image or how to build from source).

FWIW what I'm running into is errors building like:
```
'/opt/homebrew/Cellar/dotnet/8.0.0/libexec/shared/Microsoft.NETCore.App/8.0.0/FreeImage' (no such file)
```

I have tried `brew install freeimage`

**Comment by dps** [comment]
tbc, I'm talking about how to run the game, not the solutions -- thanks much!

**Comment by stevehjohn** [comment]
Ah, yep. I'll update the README.md file.

In the meantime, this should hopefully fix it for you:

- `brew install freeimage`
- `mkdir /usr/local/lib` (this folder may already exist, in which case this step is not needed).
- `sudo ln -s /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage.dylib /usr/local/lib/libfreeimage`
- `brew install freetype`
- `sudo ln -s /opt/homebrew/lib/libfreetype.6.dylib /usr/local/lib/libfreetype6`

Please let me know if this fixes it for you, I want people to be able to easily enjoy the game.

Thanks,

Steve.

**Comment by stevehjohn** [comment]
Have updated the [README.md file](https://github.com/stevehjohn/AoC/tree/master/AoC.Games#readme).

**Comment by stevehjohn** [comment]
Have also uploaded a new release that allows scaling of the window in a settings file. Details in the README linked previously.

**Comment by stevehjohn** [comment]
Have added a script to hopefully automate the dependency install. Details here: https://github.com/stevehjohn/AoC/tree/master/AoC.Games#other-dependencies-for-macos

**Comment by dps** [comment]
Thanks! I got it to work, but not by following the script exactly - I ended up having to create symlinks in different directories:

```
 sudo ln -s /opt/homebrew/Cellar/freeimage/3.18.0/lib/libfreeimage.dylib /opt/homebrew/Cellar/dotnet/8.0.0/libexec/shared/Microsoft.NETCore.App/8.0.0/FreeImage.dylib
 sudo ln -s /opt/homebrew/lib/libfreetype.6.dylib /opt/homebrew/Cellar/dotnet/8.0.0/libexec/shared/Microsoft.NETCore.App/8.0.0/freetype6
```

^ this worked, the `/usr/local/lib/` symlinks did not, even with `export DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH`

**Comment by stevehjohn** [comment]
Great, glad you got it working.
